events {
    worker_connections 1024;
}

http {
    # Upstream for API Gateway
    upstream apigateway {
        server apigateway:8080;
    }

    # Upstream for MinIO
    upstream minio {
        server minio:9000;
    }

    server {
        listen 8080;
        server_name _;

        # API Gateway
        location /api/ {
            proxy_pass         http://apigateway;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            # Support large uploads / streaming downloads
            proxy_request_buffering  off;
            proxy_buffering          off;
            client_max_body_size     0;
        }

        # API Docs
        location /docs/ {
            proxy_pass         http://apigateway;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /download {
            proxy_pass         http://apigateway;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_request_buffering  off;
            proxy_buffering          off;
            client_max_body_size     0;
        }

        # Public frontend
        location / {
            proxy_pass         http://public;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        # MinIO object storage — exposed under /storage/
        # Presigned URLs will use http://localhost/storage/...
#         location /storage/ {
#             rewrite            ^/storage/(.*) /$1 break;
#             proxy_pass         http://minio;
#             proxy_set_header   Host              minio;
#             proxy_set_header   X-Real-IP         $remote_addr;
#             proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
#             proxy_set_header   X-Forwarded-Proto $scheme;
#
#             proxy_request_buffering  off;
#             proxy_buffering          off;
#             client_max_body_size     0;
#         }
    }

    server {
        listen 9000;
        server_name minio;
        location / {
            proxy_pass         http://minio;
        }
    }
}

