FROM debian:12-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends wget netcat-openbsd ca-certificates \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY deployments/create-bucket.sh /app/create-bucket.sh
RUN chmod +x /app/create-bucket.sh
ENTRYPOINT ["/app/create-bucket.sh"]
