// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type DownloadTask struct {
	ID             uint64 `json:"id"`
	OfAccountID    uint64 `json:"of_account_id"`
	DownloadType   int16  `json:"download_type"`
	Url            string `json:"url"`
	DownloadStatus int16  `json:"download_status"`
	Metadata       string `json:"metadata"`
}
