// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Account struct {
	AccountID   uint64 `json:"account_id"`
	AccountName string `json:"account_name"`
}

type AccountPassword struct {
	OfAccountID    uint64 `json:"of_account_id"`
	HashedPassword string `json:"hashed_password"`
}
