// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type Task struct {
	ID              uint64          `json:"id"`
	OfAccountID     uint64          `json:"of_account_id"`
	FileName        string          `json:"file_name"`
	SourceUrl       string          `json:"source_url"`
	SourceType      string          `json:"source_type"`
	Headers         json.RawMessage `json:"headers"`
	SourceAuth      json.RawMessage `json:"source_auth"`
	StorageType     string          `json:"storage_type"`
	StoragePath     string          `json:"storage_path"`
	ChecksumType    sql.NullString  `json:"checksum_type"`
	ChecksumValue   sql.NullString  `json:"checksum_value"`
	Concurrency     sql.NullInt32   `json:"concurrency"`
	MaxSpeed        sql.NullInt64   `json:"max_speed"`
	MaxRetries      int32           `json:"max_retries"`
	Timeout         sql.NullInt32   `json:"timeout"`
	Status          string          `json:"status"`
	Progress        sql.NullFloat64 `json:"progress"`
	DownloadedBytes sql.NullInt64   `json:"downloaded_bytes"`
	TotalBytes      sql.NullInt64   `json:"total_bytes"`
	ErrorMessage    sql.NullString  `json:"error_message"`
	Metadata        json.RawMessage `json:"metadata"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	CompletedAt     sql.NullTime    `json:"completed_at"`
	LastAccessedAt  sql.NullTime    `json:"last_accessed_at"`
	ExpirationDays  sql.NullInt32   `json:"expiration_days"`
}
