// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type Task struct {
	ID          uint64          `json:"id"`
	OfAccountID uint64          `json:"of_account_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	SourceUrl   string          `json:"source_url"`
	SourceType  string          `json:"source_type"`
	SourceAuth  json.RawMessage `json:"source_auth"`
	StorageType string          `json:"storage_type"`
	StoragePath string          `json:"storage_path"`
	Status      string          `json:"status"`
	FileInfo    json.RawMessage `json:"file_info"`
	Progress    json.RawMessage `json:"progress"`
	Options     json.RawMessage `json:"options"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
	CompletedAt sql.NullTime    `json:"completed_at"`
	Error       sql.NullString  `json:"error"`
	RetryCount  int32           `json:"retry_count"`
	MaxRetries  int32           `json:"max_retries"`
	Tags        json.RawMessage `json:"tags"`
	Metadata    json.RawMessage `json:"metadata"`
}
