log:
  level: "debug"
mysql:
  host: mysql
  port: 3306
  username: root
  password: example
  database: goload
redis:
  address: "redis:6379"
  username: ""
  password: ""
auth:
  hash:
    bcrypt:
      hash_cost: 10
  token:
    jwt_rs512:
      rsa_bits: 2048
    expires_in: 24h
    regenerate_token_before_expiry: 1h
apigateway:
  http:
    address: "0.0.0.0:8080"
  token_hmac_secret: "dev-secret-123456"
  storage:
    minio:
      endpoint: "http://minio:9000"
      access_key: "minioadmin"
      secret_key: "minioadmin"
      bucket: "goload"
      use_ssl: false
authservice:
  grpc:
    # inside docker-compose, use the service container name so other containers can reach it
    address: "authsvc:8081"
downloadtaskservice:
  grpc:
    address: "task:8082"
fileservice:
  grpc:
    address: "fileservice:8083"
messaging:
  kafka:
    brokers: ["broker:9092"]
    version: "4.0.0"
    consumer_group: "download-service-group"
